version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "capstone-app-task"
        LoadBalancerInfo:
          ContainerName: "capstone-container"
          ContainerPort: 3000
